# Generated by Django 3.0.2 on 2020-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0010_facultyprofile_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
