# Generated by Django 3.0.2 on 2020-02-16 06:17

import taggit_selectize.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('profiles', '0012_facultyprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='interests',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                            through='taggit.TaggedItem', to='taggit.Tag',
                                                            verbose_name='Tags'),
        ),
    ]
