# Generated by Django 3.0.2 on 2020-02-18 15:29

import ckeditor.fields
import taggit_autosuggest.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('profiles', '0013_auto_20200216_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='about',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='articles',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='interests',
            field=taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                              through='taggit.TaggedItem', to='taggit.Tag',
                                                              verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='projects',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='about',
            field=models.CharField(max_length=10000),
        ),
    ]
