# Generated by Django 3.0.2 on 2020-03-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0014_auto_20200218_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('faculty',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.FacultyProfile')),
                ('student',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
