# Generated by Django 3.0.2 on 2020-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0015_auto_20200307_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_reject',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
