# Generated by Django 3.0.2 on 2020-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0016_appointment_reason_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
