# Generated by Django 3.0.2 on 2020-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0017_auto_20200310_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
