# Generated by Django 3.0.2 on 2020-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0018_auto_20200313_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
