# Generated by Django 3.0.2 on 2020-03-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0019_auto_20200313_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.FacultyProfile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentProfile'),
        ),
    ]
